app:
  context-path: /api/v1/catalog
server:
  port: 8080
spring:
  application:
    name: eshop-catalog-service
  r2dbc:
    url: r2dbc:postgresql://postgres@localhost:5432
    name: eshop-product-catalog
    username: postgres
    password: postgres
logging:
  level:
    org.springframework.r2dbc: debug
    org.springframework.web: debug
    root: warn