app:
  context-path: /api/v1/catalog
  endpoints:
    categories: /categories
logging:
  level:
    org.springframework.web: debug
    org.springframework.web.reactive: debug
server:
  port: 8080
spring:
  application:
    name: eshop-product-catalog
  data:
    mongodb:
      port: 27017
      host: localhost
      username: dksifoua
      password: dksifoua
      database: admin
      authentication-database: admin
      auto-index-creation: true
