DROP TABLE IF EXISTS CATEGORY;
CREATE TABLE CATEGORY (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(256) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(512),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);